name: tastefinder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - sqlalchemy
  - psycopg2
  - requests
  - beautifulsoup4
  - lxml               # Parsing de HTML, ajuda o BeautifulSoup
  - flask
  - pip:
      - python-dotenv  # Para variáveis de ambiente
